version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: books_store_db_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_store_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
